routes/web.php
<?php
use Illuminate\Http\Request;


Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('/login', ['as' => 'post.login', 'uses' => 'Auth\LoginController@login']);
Route::post('/logout', ['as' => 'post.logout', 'uses' => 'Auth\LoginController@logout']);

Route::get('/img/{path}', ['as' => 'image', 'uses' => function(League\Glide\Server $server, $path) {
    return $server->getImageResponse($path, $_GET);
}])->where('path', '.+');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Backend'], function() {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'BackendController@dashboard']);

    Route::resource('slider', 'SliderController', ['except' => ['show']]);
    Route::resource('customer', 'CustomerController', ['except' => ['show']]);
    Route::resource('post', 'PostController', ['except' => ['show'] ]);
    Route::resource('project', 'ProjectController', ['except' => ['show']]);
    Route::resource('product', 'ProductController', ['except' => ['show'] ]);
    Route::resource('designer', 'DesignerController', ['except' => ['show'] ]);
    Route::resource('category', 'CategoryController', ['except' => ['show'] ]);
    Route::resource('stage', 'StageController', ['except' => ['index', 'show']]);
    Route::resource('tag','TagController', ['except' => ['show', 'store', 'edit', 'update'] ]);
    Route::resource('setting', 'SettingController', ['except' => ['show', 'create', 'store', 'destroy'] ]);

    Route::get('/media/{id}', ['as' => 'media.preview', 'uses' => 'MediaController@preview']);
    Route::delete('/media/{id}', ['as' => 'media.destroy', 'uses' => 'MediaController@destroy']);
    Route::post('/media/document', ['as' => 'media.document.store', 'uses' => 'MediaController@storeDocument']);
    Route::post('/media/image', ['as' => 'media.image.store', 'uses' => 'MediaController@storeImage']);
    Route::post('/media/image/thumbnail', ['as' => 'media.image.thumbnail', 'uses' => 'MediaController@changeThumbnail']);
});

Route::get('project/{id}', ['as' => 'project.show', 'uses' => 'Backend\ProjectController@show']);

Route::group(['namespace'=>'Frontend', 'as' => 'frontend.'], function(){
    Route::get('/', ['as' => 'index', 'uses' => 'HomeController@index']);
    Route::get('bai-viet',['as'=>'post.index','uses'=>'PostController@index']);
    Route::get('bai-viet/{post_slug}',['as'=>'post.show','uses'=>'PostController@show']);
    Route::get('{slug}',['as'=>'slug.show','uses'=>'SlugController@index']);
});

app/Post.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Cartalyst\Tags\TaggableTrait;
use Cartalyst\Tags\TaggableInterface;
use Plank\Mediable\Mediable;
use App\Traits\HasImages;
use App\Traits\VnDateTrait;

class Post extends Model implements TaggableInterface
{
    use Sluggable, TaggableTrait, Mediable, HasImages, VnDateTrait;

    const STATUS_DRAFT = 'DRAFT';
    const STATUS_PUBLISH = 'PUBLISH';
    const STATUSES = [ self::STATUS_DRAFT, self::STATUS_PUBLISH ];

    public $incrementing = false;

    protected $fillable = ['id', 'author', 'title', 'content', 'featured', 'status', 'description', 'meta_title', 'meta_description'];
    protected $casts = [
        'featured' => 'boolean',
    ];
    protected $attributes = [
        'author' => '',
        'featured' => false,
        'status' => self::STATUS_DRAFT,
    ];


    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function scopeFeatured($query)
    {
        return $query->whereFeatured(true);
    }

    public function scopePublished($query)
    {
        return $query->whereStatus(self::STATUS_PUBLISH);
    }

    public function getMetaTitleAttribute($value)
    {
        if(! $value) {
            return $this->attributes['title'];
        }
        return $value;
    }

    public function getMetaDescriptionAttribute($value)
    {
        if(! $value) {
            return str_limit($this->attributes['description'], 150);
        }
        return str_limit($value, 150);
    }

    public function setMetaDescriptionAttribute($value)
    {
        $this->attributes['meta_description'] = str_limit($value, 150);
    }

    public function getCreatedAtAttribute($value)
    {
        return $this->getDate($value);
    }

}

app/Slider.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Plank\Mediable\Mediable;

class Slider extends Model
{
    use Mediable;

    public $incrementing = false;
    protected $fillable = ['id', 'url', 'heading', 'heading_size', 'heading_color', 'description', 'description_size', 'description_color'];
    protected $attributes = [
        'heading_size' => '62px',
        'heading_color' => '#fff',
        'description_size' => '14px',
        'description_color' => '#fff',
    ];

    public function images()
    {
        return $this->morphToMany(Image::class, 'mediable', 'mediables', 'mediable_id', 'media_id')
            ->where('aggregate_type', Image::TYPE_IMAGE)
            ->withPivot('tag', 'order')
            ->orderBy('order');
    }

    public function attachImage($images_id)
    {
        $tag = "slider_{$this->id}";
        $current = $this->firstMedia($tag);

        if($current && count($images_id) == 1 && $images_id[0] == $current->id) {
            return;
        } else if(count($images_id) > 1){
            $images_id = array_filter($images_id, function($id) use ($current) {
                return $id !== $current->id;
            });
            $this->detachMediaTags($tag);
        }

        $this->attachMedia($images_id, $tag);
    }

    public function getHeadingSizePixelAttribute($value)
    {
        return is_null($this->heading_size) ? "100%" : "{$this->heading_size}px";
    }

    public function getDescriptionSizePixelAttribute($value)
    {
        return is_null($this->description_size) ? "100%" : "{$this->description_size}px";
    }
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Contracts\Repositories\PostRepositoryInterface;
use App\Contracts\Repositories\ProductRepositoryInterface;
use App\Contracts\Repositories\SliderRepositoryInterface;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    protected $sliders;
    protected $products;
    protected $posts;

    public function __construct(SliderRepositoryInterface $sliders, ProductRepositoryInterface $products, PostRepositoryInterface $posts)
    {
        $this->products = $products;
        $this->sliders = $sliders;
        $this->posts = $posts;
    }

    public function index()
    {
        $sliders = $this->sliders->all();
        $featuredProducts = $this->products->featured()->limit(9)->get();
        $featuredPosts = $this->posts->featured()->published()->limit(9)->get();

        // dd(compact('sliders'));
        return view('frontend.home', compact('sliders', 'featuredProducts', 'featuredPosts'));
    }
}

app/Http/Controllers/Frontend/PostController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Contracts\Repositories\PostRepositoryInterface;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{

    protected $posts;

    public function __construct(PostRepositoryInterface $posts)
    {
    	$this->posts = $posts;
    }

	public function index()
	{
		$posts = $this->posts->published()->paginate(9);
		return view('frontend.post.index',['posts' => $posts]);
	}

	public function show($post_slug)
	{
		$post = $this->posts->findBySlug($post_slug);
		if($post && $post->status == Post::STATUS_PUBLISH) {
            $featuredPosts = $this->posts->published()->featured()->limit(3)->get();
			return view('frontend.post.show', compact('post', 'featuredPosts'));
		}
		return abort(404);
	}

}

app/Http/Controllers/Frontend/SlugController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Contracts\Repositories\ProductRepositoryInterface;
use App\Contracts\Repositories\CategoryRepositoryInterface;


class SlugController extends Controller
{
    protected $products;
    protected $categories;

    public function __construct(ProductRepositoryInterface $products, CategoryRepositoryInterface $categories)
    {
    	$this->products = $products;
        $this->categories = $categories;
    }

    public function index($slug)
    {
        if($product = $this->products->findBySlug($slug)) {
            return view('frontend.product.show', ['product' => $product]);
        } else if($category = $this->categories->findBySlug($slug)) {
            if(! $category->isCategorizable) {
                return view('frontend.product.index', ['category' => $category, 'products' => $category->childrenProducts()->paginate(16)]);
            }

            $products = $this->products->paginateByCategorySlug($slug, 12);
            return view('frontend.product.index', ['category' => $category, 'products' => $products]);
        }
        return abort(404);
    }
}

resources/views/frontend/home.blade.php
@extends('layouts.frontend')
@section('title', 'Trang Chủ')

@section('content')
<div class="slider">
	<div class="fullwidthbanner-container">
		<div class="fullwidthbanner">
			<ul>
                @foreach($sliders as $slider)
				<li class="first-slide" data-transition="fade" data-slotamount="10" data-masterspeed="300">
					<img src="{{ $slider->images->first()->url or asset('files/images/01-slide.jpg') }}" data-fullwidthcentering="on" alt="slide">
					<div class="tp-caption first-line lft tp-resizeme start" data-x="center" data-hoffset="0" data-y="250" data-speed="1000" data-start="200" data-easing="Power4.easeOut" data-splitin="none" data-splitout="none" data-elementdelay="0" data-endelementdelay="0"
                    style = "
                        @if($slider->heading_size) font-size: {{ $slider->heading_size_pixel }} @endif;
                        @if($slider->heading_color) color: {{ $slider->heading_color }} @endif;
                    ">
                        {{ $slider->heading or '' }}
                    </div>
					<div class="tp-caption second-line lfb tp-resizeme start" data-x="center" data-hoffset="0" data-y="440" data-speed="1000" data-start="800" data-easing="Power4.easeOut" data-splitin="none" data-splitout="none" data-elementdelay="0" data-endelementdelay="0"
                    style = "
                        @if($slider->description_size) font-size: {{ $slider->description_size_pixel }} @endif;
                        @if($slider->description_color) color: {{ $slider->description_color }} @endif;
                    ">
                        {{ $slider->description or '' }}
                    </div>
                    @if($slider->url)
					<div class="tp-caption slider-btn sfb tp-resizeme start" data-x="center" data-hoffset="0" data-y="510" data-speed="1000" data-start="2200" data-easing="Power4.easeOut" data-splitin="none" data-splitout="none" data-elementdelay="0" data-endelementdelay="0"><a href="{{ $slider->url }}" class="btn btn-slider">Xem Thêm</a></div>
                    @endif
				</li>
				@endforeach
			</ul>
		</div>
	</div>
</div>
<div class="clearfix"></div>


<section class="portfolio">
	<div class="container">
		<div class="section-heading">
			<h2 style="color: #fff">Sản Phẩm Bán Chạy</h2>
			<div style="background-color: #fff" class="section-dec"></div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div id="owl-demo" class="owl-carousel owl-theme">
                    @foreach($featuredProducts as $product)
					<div class="item">
                        <a href="{{ route('frontend.slug.show', ['slug' => $product->slug]) }}">
                            <figure>
                                <img alt="portfolio" src="{{ $product->thumbnail !== null ? $product->thumbnail->getUrl() : asset('files/images/01-portfolio.jpg') }}">
                                <figcaption>
                                    <h3>{{ $product->name }}</h3>
                                    <p>{{ str_limit($product->description, 100) }}</p>
                                </figcaption>
                            </figure>
                        </a>
                    </div>
                    @endforeach
				</div>
			</div>
		</div>
	</div>
</section>


<section class="blog-posts">
    <div class="container">
        <div class="section-heading">
            <h2>Những Bài Viết Mới</h2>
            <div class="section-dec"></div>
        </div>
        <div class="row">
            <div class="owl-navigation">
                <a class="btn prev fa fa-angle-left"></a>
                <a class="btn next fa fa-angle-right"></a>
            </div>
            <div class="col-md-12">
                <div id="owl-portfolio" class="owl-carousel owl-theme owl-navigation">
                    @foreach($featuredPosts as $post)
                    <div class="item blog-item">
                        <figure>
                            <a href="{{ route('frontend.post.show', $post->slug) }}">
                                <img src="{{ $post->thumbnail !== null ? $post->thumbnail->getUrl() : asset('files/images/01-portfolio.jpg') }}" alt="">
                            </a>
                            <h3><a href="{{ route('frontend.post.show', $post->slug) }}">{{ str_limit($post->title, 25) }}</a></h3>
                            <span>
                                @if($post->author)
                                    <a href="">{{ $post->author or '' }}</a> -
                                @endif
                                <a href="">{{ $post->created_at }}</a>
                            </span>
                            <p>{{ str_limit($post->description, 100) }}</p>
                            <div class="read-more">
                                <a href="{{ route('frontend.post.show', $post->slug) }}">Xem Thêm</a>
                            </div>
                        </figure>
                    </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</section>
@endsection