routes/web.php
<?php
use Illuminate\Http\Request;


Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('/login', ['as' => 'post.login', 'uses' => 'Auth\LoginController@login']);
Route::post('/logout', ['as' => 'post.logout', 'uses' => 'Auth\LoginController@logout']);

Route::get('/img/{path}', ['as' => 'image', 'uses' => function(League\Glide\Server $server, $path) {
    return $server->getImageResponse($path, $_GET);
}])->where('path', '.+');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Backend'], function() {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'BackendController@dashboard']);

    Route::resource('slider', 'SliderController', ['except' => ['show']]);
    Route::resource('customer', 'CustomerController', ['except' => ['show']]);
    Route::resource('post', 'PostController', ['except' => ['show'] ]);
    Route::resource('project', 'ProjectController', ['except' => ['show']]);
    Route::resource('product', 'ProductController', ['except' => ['show'] ]);
    Route::resource('designer', 'DesignerController', ['except' => ['show'] ]);
    Route::resource('category', 'CategoryController', ['except' => ['show'] ]);
    Route::resource('stage', 'StageController', ['except' => ['index', 'show']]);
    Route::resource('tag','TagController', ['except' => ['show', 'store', 'edit', 'update'] ]);
    Route::resource('setting', 'SettingController', ['except' => ['show', 'create', 'store', 'destroy'] ]);

    Route::get('/media/{id}', ['as' => 'media.preview', 'uses' => 'MediaController@preview']);
    Route::delete('/media/{id}', ['as' => 'media.destroy', 'uses' => 'MediaController@destroy']);
    Route::post('/media/document', ['as' => 'media.document.store', 'uses' => 'MediaController@storeDocument']);
    Route::post('/media/image', ['as' => 'media.image.store', 'uses' => 'MediaController@storeImage']);
    Route::post('/media/image/thumbnail', ['as' => 'media.image.thumbnail', 'uses' => 'MediaController@changeThumbnail']);
});

Route::get('project/{id}', ['as' => 'project.show', 'uses' => 'Backend\ProjectController@show']);

Route::group(['namespace'=>'Frontend', 'as' => 'frontend.'], function(){
    Route::get('/', ['as' => 'index', 'uses' => 'HomeController@index']);
    Route::get('bai-viet',['as'=>'post.index','uses'=>'PostController@index']);
    Route::get('bai-viet/{post_slug}',['as'=>'post.show','uses'=>'PostController@show']);
    Route::get('{slug}',['as'=>'slug.show','uses'=>'SlugController@index']);
});

app/Http/Controllers/Backend/BackendController.php
<?php
namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BackendController extends Controller
{

    public function dashboard(Request $request)
    {
        return view('backend.dashboard');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php
namespace App\Http\Controllers\Backend;

use Ramsey\Uuid\Uuid;
use App\Traits\ExecuteCommandTrait;
use App\Jobs\Category\CreateCategory;
use App\Jobs\Category\DeleteCategory;
use App\Jobs\Category\UpdateCategory;
use App\Contracts\DataTables\CategoryDataTableInterface;
use App\Contracts\Repositories\CategoryRepositoryInterface;

use App\Http\Requests;
use Illuminate\Http\Request;

class CategoryController extends BackendController
{
    use ExecuteCommandTrait;

    private $categories;
    private $dataTable;

    public function __construct(CategoryRepositoryInterface $categories, CategoryDataTableInterface $dataTable)
    {
        $this->categories = $categories;
        $this->dataTable = $dataTable;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            return $this->dataTable->getData();
        }
        return view('backend.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if($request->ajax()) {
            if($input = $request->input('q'))
                return $this->categories->paginateNameLike($input);
            return $this->categories->paginate();
        }

        return view('backend.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = (string) Uuid::uuid4();
        $attributes = array_merge($request->all(), [
            'id' => $id,
            'parent_id' => $this->categories->findBy('name', $request->parent)->id,
        ]);

        $this->executeCommand(new CreateCategory($attributes));
        flash('Created Successfully', 'success');
        return redirect()->route('admin.category.edit', ['id' => $id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $category = $this->categories->find($id);
        return view('backend.category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categories->find($id);
        return view('backend.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $attributes = array_merge($request->all(), [
            'parent_id' => $this->categories->findBy('name', $request->parent)->id,
        ]);

        $this->executeCommand(new UpdateCategory($id, $request->all()));
        flash('Edited Successfully', 'success');
        return redirect()->route('admin.category.edit', ['id' => $id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->executeCommand(new DeleteCategory($id));
        flash('Deleted Successfully', 'success');
        return redirect()->route('admin.category.index');
    }
}

app/Http/Controllers/Backend/CustomerController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Contracts\DataTables\CustomerDataTableInterface;
use App\Contracts\Repositories\CustomerRepositoryInterface;
use App\Http\Controllers\Controller;
use App\Jobs\Customer\CreateCustomer;
use App\Jobs\Customer\DeleteCustomer;
use App\Jobs\Customer\UpdateCustomer;
use App\Traits\ExecuteCommandTrait;
use Illuminate\Http\Request;
use Ramsey\Uuid\Uuid;

class CustomerController extends Controller
{
    use ExecuteCommandTrait;

    private $customers;
    private $dataTable;

    public function __construct(CustomerRepositoryInterface $customers, CustomerDataTableInterface $dataTable)
    {
        $this->customers = $customers;
        $this->dataTable = $dataTable;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            return $this->dataTable->getData();
        }
        return view('backend.customer.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if($request->ajax()) {
            if($input = $request->input('q')) {
                return $this->customers->paginateNameLike($input);
            }
            return $this->customers->paginate();
        }
        return view('backend.customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = Uuid::uuid4()->toString();
        $attributes = array_merge(['id' => $id], $request->all());
        $this->executeCommand(new CreateCustomer($attributes));
        return redirect()->route('admin.customer.edit', ['id' => $id]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = $this->customers->find($id);
        return view('backend.customer.edit', compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->executeCommand(new UpdateCustomer($id, $request->all()));
        return redirect()->route('admin.customer.edit', ['id' => $id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->executeCommand(new DeleteCustomer($id));
        return redirect()->route('admin.customer.index');
    }
}

app/Http/Controllers/Backend/DesignerController.php
<?php
namespace App\Http\Controllers\Backend;

use Ramsey\Uuid\Uuid;
use App\Traits\ExecuteCommandTrait;
use App\Jobs\Designer\CreateDesigner;
use App\Jobs\Designer\DeleteDesigner;
use App\Jobs\Designer\UpdateDesigner;

use App\Contracts\DataTables\DesignerDataTableInterface;
use App\Contracts\Repositories\DesignerRepositoryInterface;
use App\Http\Requests;
use Illuminate\Http\Request;

class DesignerController extends BackendController
{
    use ExecuteCommandTrait;

    private $designers;
    private $dataTable;

    public function __construct(DesignerRepositoryInterface $designers, DesignerDataTableInterface $dataTable)
    {
        $this->designers = $designers;
        $this->dataTable = $dataTable;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            return $this->dataTable->getData();
        }
        return view('backend.designer.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if($request->ajax()) {
            if($input = $request->input('q')) {
                return $this->designers->paginateNameLike($input);
            }
            return $this->designers->paginate();
        }
        return view('backend.designer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = Uuid::uuid4()->toString();
        $attributes = array_merge(['id' => $id], $request->all());

        $this->executeCommand(new CreateDesigner($attributes));
        flash('Created Successfully', 'success');
        return redirect()->route('admin.designer.edit', ['id' => $id]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $designer = $this->designers->find($id);
        $designer->load('images');
        return view('backend.designer.edit', compact('designer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->executeCommand(new UpdateDesigner($id, $request->all()));
        flash('Edited Successfully', 'success');
        return redirect()->route('admin.designer.edit', ['id' => $id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->executeCommand(new DeleteDesigner($id));
        flash('Deleted Successfully', 'success');
        return redirect()->route('admin.designer.index');
    }
}

app/Http/Controllers/Backend/MediaController.php
<?php
namespace App\Http\Controllers\Backend;

use App\Contracts\Repositories\MediaRepositoryInterface;
use App\Http\Requests;
use App\Jobs\Media\ChangeThumbnail;
use App\Jobs\Media\DeleteMedia;
use App\Jobs\Media\UploadDocument;
use App\Jobs\Media\UploadImage;
use App\Traits\ExecuteCommandTrait;
use Approached\LaravelImageOptimizer\ImageOptimizer;
use Illuminate\Http\Request;
use Ramsey\Uuid\Uuid;


class MediaController extends BackendController
{
    use ExecuteCommandTrait;

	private $medias;

    public function __construct(MediaRepositoryInterface $medias)
    {
        $this->medias = $medias;
    }

    public function storeDocument(Request $request)
    {
        return $this->executeCommand(new UploadDocument([
            'id' => Uuid::uuid4()->toString(),
            'file' => $request->document
        ]));
    }

    public function storeImage(Request $request, ImageOptimizer $imageOptimizer)
    {
        $imageOptimizer->optimizeUploadedImageFile($request->image);
        return $this->executeCommand(new UploadImage([
            'id' => Uuid::uuid4()->toString(),
            'file' => $request->image
        ]));
    }

    public function destroy($id)
    {
        $this->executeCommand(new DeleteMedia($id));
    }

    public function changeThumbnail(Request $request)
    {
        $this->executeCommand(new ChangeThumbnail($request->all()));
        return $this->medias->image()->find($request->image_id);
    }

    public function preview($id)
    {
        $media = $this->medias->find($id);
        $file = \Storage::disk($media->disk)->get("{$media->filename}.{$media->extension}");
        return response()->make($file, 200, ['Content-Type' => $media->mime_type]);
    }
}

app/Http/Controllers/Backend/ProjectController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Contracts\DataTables\ProjectDataTableInterface;
use App\Contracts\Repositories\CustomerRepositoryInterface;
use App\Contracts\Repositories\ProjectRepositoryInterface;
use App\Jobs\Project\CreateProject;
use App\Jobs\Project\DeleteProject;
use App\Jobs\Project\UpdateProject;
use App\Traits\ExecuteCommandTrait;
use Illuminate\Http\Request;
use Ramsey\Uuid\Uuid;

class ProjectController extends BackendController
{
    use ExecuteCommandTrait;


    private $projects;
    private $dataTable;
    private $customers;

    public function __construct(ProjectRepositoryInterface $projects, ProjectDataTableInterface $dataTable, CustomerRepositoryInterface $customers)
    {
        $this->projects = $projects;
        $this->dataTable = $dataTable;
        $this->customers = $customers;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            return $this->dataTable->getData();
        }
        return view('backend.project.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.project.create');
    }

    public function show($id)
    {
        $project = $this->projects->find($id);
        return view('backend.project.show', compact('project'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = Uuid::uuid4()->toString();
        $attributes = array_merge($request->all(), [
            'id' => $id,
            'customer_id' => $this->customers->firstOrcreate(['name' => $request->customer])->id,
        ]);

        $this->executeCommand(new CreateProject($attributes));
        flash('Create Successfully', 'success');
        return redirect()->route('admin.project.edit', ['id' => $id]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = $this->projects->find($id);
        return view('backend.project.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $attributes = array_merge($request->all(), [
            'customer_id' => $this->customers->firstOrcreate(['name' => $request->customer])->id,
        ]);

        $this->executeCommand(new UpdateProject($id, $attributes));
        flash('Edited Successfully', 'success');
        return redirect()->route('admin.project.edit', ['id' => $id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->executeCommand(new DeleteProject($id));
        flash('Delete Successfully', 'success');
        return redirect()->route('admin.project.index');
    }
}

resources/views/backend/_partials/footer.blade.php
<footer class="main-footer">
    <strong><a href="#"> Khai Pham  </a></strong>
</footer>

resources/views/backend/_partials/left-sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header">Dashboard</li>

            <li class="treeview">
                <a href="{{ route('admin.category.index') }}">
                    <i class="fa fa-list"></i>
                    <span>Category</span>
                </a>
            </li>

            <li class="treeview">
                <a href="{{ route('admin.product.index') }}">
                    <i class="fa fa-shopping-cart"></i>
                    <span>Product</span>
                </a>
            </li>

            <!-- <li class="treeview">
                <a href="{{ route('admin.tag.index') }}">
                    <i class="fa fa-tags"></i>
                    <span>Tag</span>
                </a>
            </li> -->

            <li class="treeview">
                <a href="{{ route('admin.post.index') }}">
                    <i class="fa fa-book"></i>
                    <span>Post</span>
                </a>
            </li>

            <li class="treeview">
                <a href="{{ route('admin.designer.index') }}">
                    <i class="fa fa-user"></i>
                    <span>Designer</span>
                </a>
            </li>

             <li class="treeview">
                <a href="{{ route('admin.customer.index') }}">
                    <i class="fa fa-users"></i>
                    <span>Customer</span>
                </a>
            </li>

            <li class="treeview">
                <a href="{{ route('admin.project.index') }}">
                    <i class="fa fa-files-o"></i>
                    <span>Project</span>
                </a>
            </li>

            <li class="treeview">
                <a href="{{ route('admin.slider.index') }}">
                    <i class="fa fa-photo"></i>
                    <span>Slider</span>
                </a>
            </li>

            <li class="treeview">
                <a href="{{ route('admin.setting.index') }}">
                    <i class="fa fa-cog"></i>
                    <span>Setting</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/backend/_partials/navbar.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ route('admin.dashboard') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>KP</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Khai Pham</b>Admin</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                     <img src="{{ asset('assets/vendor/adminlte/img/user2-160x160.jpg') }}" class="user-image" alt="User Image">
                    <span class="hidden-xs">{{ $me->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{{ asset('assets/vendor/adminlte/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
                <p>
                  {{ $me->name }}
                </p>
              </li>
                <div class="pull-right">
                    <form action="{{ route('post.logout') }}" method="POST">
                         {{ csrf_field() }}
                        <button type="submit" class="btn btn-default btn-flat">Sign out</button>
                    </form>
                </div>
              </li>
            </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>