routes/web.php
<?php
use Illuminate\Http\Request;


Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('/login', ['as' => 'post.login', 'uses' => 'Auth\LoginController@login']);
Route::post('/logout', ['as' => 'post.logout', 'uses' => 'Auth\LoginController@logout']);

Route::get('/img/{path}', ['as' => 'image', 'uses' => function(League\Glide\Server $server, $path) {
    return $server->getImageResponse($path, $_GET);
}])->where('path', '.+');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Backend'], function() {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'BackendController@dashboard']);

    Route::resource('slider', 'SliderController', ['except' => ['show']]);
    Route::resource('customer', 'CustomerController', ['except' => ['show']]);
    Route::resource('post', 'PostController', ['except' => ['show'] ]);
    Route::resource('project', 'ProjectController', ['except' => ['show']]);
    Route::resource('product', 'ProductController', ['except' => ['show'] ]);
    Route::resource('designer', 'DesignerController', ['except' => ['show'] ]);
    Route::resource('category', 'CategoryController', ['except' => ['show'] ]);
    Route::resource('stage', 'StageController', ['except' => ['index', 'show']]);
    Route::resource('tag','TagController', ['except' => ['show', 'store', 'edit', 'update'] ]);
    Route::resource('setting', 'SettingController', ['except' => ['show', 'create', 'store', 'destroy'] ]);

    Route::get('/media/{id}', ['as' => 'media.preview', 'uses' => 'MediaController@preview']);
    Route::delete('/media/{id}', ['as' => 'media.destroy', 'uses' => 'MediaController@destroy']);
    Route::post('/media/document', ['as' => 'media.document.store', 'uses' => 'MediaController@storeDocument']);
    Route::post('/media/image', ['as' => 'media.image.store', 'uses' => 'MediaController@storeImage']);
    Route::post('/media/image/thumbnail', ['as' => 'media.image.thumbnail', 'uses' => 'MediaController@changeThumbnail']);
});

Route::get('project/{id}', ['as' => 'project.show', 'uses' => 'Backend\ProjectController@show']);

Route::group(['namespace'=>'Frontend', 'as' => 'frontend.'], function(){
    Route::get('/', ['as' => 'index', 'uses' => 'HomeController@index']);
    Route::get('bai-viet',['as'=>'post.index','uses'=>'PostController@index']);
    Route::get('bai-viet/{post_slug}',['as'=>'post.show','uses'=>'PostController@show']);
    Route::get('{slug}',['as'=>'slug.show','uses'=>'SlugController@index']);
});

app/Http/Controllers/Backend/BackendController.php
<?php
namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BackendController extends Controller
{

    public function dashboard(Request $request)
    {
        return view('backend.dashboard');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php
namespace App\Http\Controllers\Backend;

use Ramsey\Uuid\Uuid;
use App\Traits\ExecuteCommandTrait;
use App\Jobs\Category\CreateCategory;
use App\Jobs\Category\DeleteCategory;
use App\Jobs\Category\UpdateCategory;
use App\Contracts\DataTables\CategoryDataTableInterface;
use App\Contracts\Repositories\CategoryRepositoryInterface;

use App\Http\Requests;
use Illuminate\Http\Request;

class CategoryController extends BackendController
{
    use ExecuteCommandTrait;

    private $categories;
    private $dataTable;

    public function __construct(CategoryRepositoryInterface $categories, CategoryDataTableInterface $dataTable)
    {
        $this->categories = $categories;
        $this->dataTable = $dataTable;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            return $this->dataTable->getData();
        }
        return view('backend.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if($request->ajax()) {
            if($input = $request->input('q'))
                return $this->categories->paginateNameLike($input);
            return $this->categories->paginate();
        }

        return view('backend.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = (string) Uuid::uuid4();
        $attributes = array_merge($request->all(), [
            'id' => $id,
            'parent_id' => $this->categories->findBy('name', $request->parent)->id,
        ]);

        $this->executeCommand(new CreateCategory($attributes));
        flash('Created Successfully', 'success');
        return redirect()->route('admin.category.edit', ['id' => $id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $category = $this->categories->find($id);
        return view('backend.category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categories->find($id);
        return view('backend.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $attributes = array_merge($request->all(), [
            'parent_id' => $this->categories->findBy('name', $request->parent)->id,
        ]);

        $this->executeCommand(new UpdateCategory($id, $request->all()));
        flash('Edited Successfully', 'success');
        return redirect()->route('admin.category.edit', ['id' => $id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->executeCommand(new DeleteCategory($id));
        flash('Deleted Successfully', 'success');
        return redirect()->route('admin.category.index');
    }
}

app/Http/Controllers/Backend/CustomerController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Contracts\DataTables\CustomerDataTableInterface;
use App\Contracts\Repositories\CustomerRepositoryInterface;
use App\Http\Controllers\Controller;
use App\Jobs\Customer\CreateCustomer;
use App\Jobs\Customer\DeleteCustomer;
use App\Jobs\Customer\UpdateCustomer;
use App\Traits\ExecuteCommandTrait;
use Illuminate\Http\Request;
use Ramsey\Uuid\Uuid;

class CustomerController extends Controller
{
    use ExecuteCommandTrait;

    private $customers;
    private $dataTable;

    public function __construct(CustomerRepositoryInterface $customers, CustomerDataTableInterface $dataTable)
    {
        $this->customers = $customers;
        $this->dataTable = $dataTable;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            return $this->dataTable->getData();
        }
        return view('backend.customer.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if($request->ajax()) {
            if($input = $request->input('q')) {
                return $this->customers->paginateNameLike($input);
            }
            return $this->customers->paginate();
        }
        return view('backend.customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = Uuid::uuid4()->toString();
        $attributes = array_merge(['id' => $id], $request->all());
        $this->executeCommand(new CreateCustomer($attributes));
        return redirect()->route('admin.customer.edit', ['id' => $id]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = $this->customers->find($id);
        return view('backend.customer.edit', compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->executeCommand(new UpdateCustomer($id, $request->all()));
        return redirect()->route('admin.customer.edit', ['id' => $id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->executeCommand(new DeleteCustomer($id));
        return redirect()->route('admin.customer.index');
    }
}

app/Http/Controllers/Backend/DesignerController.php
<?php
namespace App\Http\Controllers\Backend;

use Ramsey\Uuid\Uuid;
use App\Traits\ExecuteCommandTrait;
use App\Jobs\Designer\CreateDesigner;
use App\Jobs\Designer\DeleteDesigner;
use App\Jobs\Designer\UpdateDesigner;

use App\Contracts\DataTables\DesignerDataTableInterface;
use App\Contracts\Repositories\DesignerRepositoryInterface;
use App\Http\Requests;
use Illuminate\Http\Request;

class DesignerController extends BackendController
{
    use ExecuteCommandTrait;

    private $designers;
    private $dataTable;

    public function __construct(DesignerRepositoryInterface $designers, DesignerDataTableInterface $dataTable)
    {
        $this->designers = $designers;
        $this->dataTable = $dataTable;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            return $this->dataTable->getData();
        }
        return view('backend.designer.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if($request->ajax()) {
            if($input = $request->input('q')) {
                return $this->designers->paginateNameLike($input);
            }
            return $this->designers->paginate();
        }
        return view('backend.designer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = Uuid::uuid4()->toString();
        $attributes = array_merge(['id' => $id], $request->all());

        $this->executeCommand(new CreateDesigner($attributes));
        flash('Created Successfully', 'success');
        return redirect()->route('admin.designer.edit', ['id' => $id]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $designer = $this->designers->find($id);
        $designer->load('images');
        return view('backend.designer.edit', compact('designer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->executeCommand(new UpdateDesigner($id, $request->all()));
        flash('Edited Successfully', 'success');
        return redirect()->route('admin.designer.edit', ['id' => $id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->executeCommand(new DeleteDesigner($id));
        flash('Deleted Successfully', 'success');
        return redirect()->route('admin.designer.index');
    }
}

app/Http/Controllers/Backend/MediaController.php
<?php
namespace App\Http\Controllers\Backend;

use App\Contracts\Repositories\MediaRepositoryInterface;
use App\Http\Requests;
use App\Jobs\Media\ChangeThumbnail;
use App\Jobs\Media\DeleteMedia;
use App\Jobs\Media\UploadDocument;
use App\Jobs\Media\UploadImage;
use App\Traits\ExecuteCommandTrait;
use Approached\LaravelImageOptimizer\ImageOptimizer;
use Illuminate\Http\Request;
use Ramsey\Uuid\Uuid;


class MediaController extends BackendController
{
    use ExecuteCommandTrait;

	private $medias;

    public function __construct(MediaRepositoryInterface $medias)
    {
        $this->medias = $medias;
    }

    public function storeDocument(Request $request)
    {
        return $this->executeCommand(new UploadDocument([
            'id' => Uuid::uuid4()->toString(),
            'file' => $request->document
        ]));
    }

    public function storeImage(Request $request, ImageOptimizer $imageOptimizer)
    {
        $imageOptimizer->optimizeUploadedImageFile($request->image);
        return $this->executeCommand(new UploadImage([
            'id' => Uuid::uuid4()->toString(),
            'file' => $request->image
        ]));
    }

    public function destroy($id)
    {
        $this->executeCommand(new DeleteMedia($id));
    }

    public function changeThumbnail(Request $request)
    {
        $this->executeCommand(new ChangeThumbnail($request->all()));
        return $this->medias->image()->find($request->image_id);
    }

    public function preview($id)
    {
        $media = $this->medias->find($id);
        $file = \Storage::disk($media->disk)->get("{$media->filename}.{$media->extension}");
        return response()->make($file, 200, ['Content-Type' => $media->mime_type]);
    }
}

app/Http/Controllers/Backend/ProjectController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Contracts\DataTables\ProjectDataTableInterface;
use App\Contracts\Repositories\CustomerRepositoryInterface;
use App\Contracts\Repositories\ProjectRepositoryInterface;
use App\Jobs\Project\CreateProject;
use App\Jobs\Project\DeleteProject;
use App\Jobs\Project\UpdateProject;
use App\Traits\ExecuteCommandTrait;
use Illuminate\Http\Request;
use Ramsey\Uuid\Uuid;

class ProjectController extends BackendController
{
    use ExecuteCommandTrait;


    private $projects;
    private $dataTable;
    private $customers;

    public function __construct(ProjectRepositoryInterface $projects, ProjectDataTableInterface $dataTable, CustomerRepositoryInterface $customers)
    {
        $this->projects = $projects;
        $this->dataTable = $dataTable;
        $this->customers = $customers;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            return $this->dataTable->getData();
        }
        return view('backend.project.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.project.create');
    }

    public function show($id)
    {
        $project = $this->projects->find($id);
        return view('backend.project.show', compact('project'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = Uuid::uuid4()->toString();
        $attributes = array_merge($request->all(), [
            'id' => $id,
            'customer_id' => $this->customers->firstOrcreate(['name' => $request->customer])->id,
        ]);

        $this->executeCommand(new CreateProject($attributes));
        flash('Create Successfully', 'success');
        return redirect()->route('admin.project.edit', ['id' => $id]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = $this->projects->find($id);
        return view('backend.project.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $attributes = array_merge($request->all(), [
            'customer_id' => $this->customers->firstOrcreate(['name' => $request->customer])->id,
        ]);

        $this->executeCommand(new UpdateProject($id, $attributes));
        flash('Edited Successfully', 'success');
        return redirect()->route('admin.project.edit', ['id' => $id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->executeCommand(new DeleteProject($id));
        flash('Delete Successfully', 'success');
        return redirect()->route('admin.project.index');
    }
}

resources/views/backend/post/_form.blade.php
<div class="box-body">
    {{ csrf_field() }}
    <div class="col-md-5">
        <div class="box-body">
                <div class="form-group">
                    <label for="author">Author *</label>
                    <input type="text" name="author" required="required" class="form-control" value="{{ isset($post) ? $post->author : old('author') }}">
                </div>

                <div class="form-group">
                    <label for="title">Title *</label>
                    <input type="text" name="title" required="required" class="form-control" value="{{ isset($post) ? $post->title : old('title') }}">
                </div>

                <div class="form-group">
                    <label for="tags">Tags</label>
                    <select name="tags[]" multiple="multiple" class="form-control select2" id="select2-post-tags">
                        @if(isset($post))
                            @foreach($post->tags as $tag)
                                <option value="{{ $tag->name }}" selected="selected">{{ $tag->name }}</option>
                            @endforeach
                        @elseif(old('tags') && is_array(old('tags')))
                            @foreach(old('tags') as $tag)
                                <option value="{{ $tag }}" selected="selected">{{ $tag }}</option>
                            @endforeach
                        @endif
                    </select>
                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" class="form-control">{{ isset($post) ? $post->description : old('description') }}</textarea>
                </div>

                <div class="form-group">
                    <label for="meta_title">Meta_title</label>
                    <input type="text" name="meta_title" class="form-control" value="{{ isset($post) ? $post->meta_title : old('meta_title') }}">
                </div>

                <div class="form-group">
                    <label for="meta_description">Meta_description</label>
                    <textarea name="meta_description" class="form-control">{{ isset($post) ? $post->meta_description : old('meta_description') }}</textarea>
                </div>

                <div class="form-group">
                    <label for="featured">Featured</label>
                    <div class="checkbox">
                        <input type="hidden" name="featured" value="off">
                        <input type="checkbox" name="featured" <?php if(isset($post) && $post->featured == true) echo "checked"?> data-toggle="toggle" data-on="Yes" data-off="No" data-onstyle="success">
                    </div>
                </div>

                <div class="form-group">
                    <label for="featured">Draft/Public</label>
                    <div class="checkbox">
                        <input type="hidden" name="status" value="off">
                        <input type="checkbox" name="status" <?php if(isset($post) && $post->status == 'PUBLISH') echo "checked"?> data-toggle="toggle" data-off="Draft" data-on="Public" data-onstyle="success">
                    </div>
                </div>
        </div>
    </div>

    <div class="col-md-7">
        <div class="box-body">
            <div class="form-group">
                <label for="images_id[]">Images</label>
                <upload-image
                    resource = "post"
                    @if(isset($post))
                        :item = "{{ $post }}"
                    @endif
                ></upload-image>
            </div>
            <div class="form-group">
                <label for="content">Content *</label>
                <wysiwyg>
                    <textarea name="content" required="required" class="form-control" slot="textarea">{{ isset($post) ? $post->content : old('content') }}</textarea>
                </wysiwyg>
            </div>
        </div>
    </div>
</div>

@push('pre-styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendor/select2/select2.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendor/summernote/summernote.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendor/bootstrap-toggle/css/bootstrap-toggle.min.css') }}">
@endpush

@push('pre-scripts')
    <script src="{{ asset('assets/vendor/select2/select2.full.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/summernote/summernote.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootstrap-toggle/js/bootstrap-toggle.min.js') }}"></script>
@endpush

@push('post-scripts')
<script src="{{ asset('assets/js/backend/form.js') }}"></script>
<script>
    new Select2("#select2-post-tags", {
        placeholder: "#hashtag...",
        tags: true,
        ajax: {
            url: laroute.route("admin.tag.create"),
            processResults: function (response, params) {
                params.page = params.page || 1;
                return {
                    results: $.map(response.data, function (item) {
                        return {
                            text: item['name'],
                            id: item['name']
                        }
                    }),
                    pagination: {
                        more: response.to < response.total
                    }
                };
            },
        }
    });
</script>
@endpush

resources/views/backend/post/create.blade.php
@extends('layouts.backend')

@section('title', 'Create Post')
@section('content-header', 'Create Post')


@section('content')
    <div class="row">
        <div class="col-md-12">
            <form action="{{ route('admin.post.store') }}" method="POST" class="form-horizontal">
                @include('backend.post._form')
                <div class="box-footer">
                    <a href="javascript:window.history.back()" class="btn btn-default">Cancel</a>
                    <button type="submit" class="btn btn-primary pull-right">Create</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('pre-scripts')
    <script src="{{ asset('assets/vendor/parsley/parsley.min.js') }}"></script>
@endpush

@push('post-scripts')
  <!-- <script>
    new FormValidation().validate('form');
  </script> -->
@endpush

resources/views/backend/post/edit.blade.php
@extends('layouts.backend')

@section('title', 'Edit Post')
@section('content-header', 'Edit Post')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <form action="{{ route('admin.post.update', ['id' => $post->id]) }}" method="POST" class="form-horizontal">
                <input type="hidden" name="_method" value="PATCH">
                @include('backend.post._form')
                <div class="box-footer">
                    <a href="javascript:window.history.back()" class="btn btn-default">Cancel</a>
                    <button type="submit" class="btn btn-primary pull-right">Edit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('pre-scripts')
    <script src="{{ asset('assets/vendor/parsley/parsley.min.js') }}"></script>
@endpush

@push('post-scripts')
  <!-- <script>
    new FormValidation().validate('form');
  </script> -->
@endpush

resources/views/backend/post/index.blade.php
@extends('layouts.backend')

@push('pre-styles')
<link rel="stylesheet" type="text/css" href='{{ asset("assets/vendor/datatables-bs/css/dataTables.bootstrap.min.css") }}'>
<link rel="stylesheet" type="text/css" href='{{ asset("assets/vendor/datatables-responsive-bs/css/responsive.bootstrap.min.css") }}'>
@endpush

@section('title', 'Post')
@section('content-header', 'Post')

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <a href="{{ route('admin.post.create') }}" class="btn btn-xs btn-primary">Add New</a>
        </div>
        <div class="box-body">
            <table id="posts-table" class="table dt-responsive nowrap" cellspacing="0"  width="100%">
                <thead>
                    <tr>
                        <th width="50%">Title</th>
                        <th>Featured</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection

@push('pre-scripts')
<script src='{{ asset("assets/vendor/datatables/js/jquery.dataTables.min.js") }}' type="text/javascript"></script>
<script src='{{ asset("assets/vendor/datatables-responsive/js/dataTables.responsive.min.js") }}' type="text/javascript"></script>
<script src='{{ asset("assets/vendor/datatables-bs/js/dataTables.bootstrap.min.js") }}' type="text/javascript"></script>
<script src='{{ asset("assets/vendor/datatables-responsive-bs/js/responsive.bootstrap.js") }}' type="text/javascript"></script>
@endpush

@push('post-scripts')
<script>
    var table = new DataTables("#posts-table", {
        ajax: laroute.route('admin.post.index'),
        columns: [
            { data: 'title', name: 'title' },
            { data: 'featured', name: 'featured' },
            { data: 'status', name: 'status' },
            { data: 'actions', name: 'actions', orderable: false, searchable: false}
        ],
        order: [[1, 'asc']]
    });
</script>
@endpush